name: hmhcapp_ios
description: "Heat Mat installer app (Flutter)"
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  open_filex: ^4.4.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/front_image.jpg
    - assets/images/diagonalpatternbg.jpg
    - assets/images/hmt5_wifi.png
    - assets/images/hmh200_wifi.png
    - assets/images/ngt_wifi.png
    - assets/images/google_play_logo.png
    - assets/images/app_store_badge.png
