name: hmhcapp_ios
description: "Heat Mat installer app (Flutter)"
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ---- Firebase (reverted to your original, working set) ----
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  # ---- UI / Utils ----
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  open_filex: ^4.4.0
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  http: ^1.2.2
  shimmer: ^3.0.0
  showcaseview: ^3.0.0

  # ---- Mobile "Save As" picker (Android + iOS) ----
  flutter_file_dialog: ^3.0.2

  # ---- PURE-FLUTTER PDF viewer (UI overlays correctly) ----
  syncfusion_flutter_pdfviewer: ^29.1.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdfs/
    # Factsheets
    - assets/pdfs/FACTSHEETS/
    - assets/pdfs/FACTSHEETS/CBM/
    - assets/pdfs/FACTSHEETS/HMHCAB/
    - assets/pdfs/FACTSHEETS/HMHMAT/
    - assets/pdfs/FACTSHEETS/ICEANDSNOW/
    - assets/pdfs/FACTSHEETS/PKC/
    - assets/pdfs/FACTSHEETS/PKM/
    - assets/pdfs/FACTSHEETS/THERMOSTATS/
    - assets/pdfs/FACTSHEETS/THERMOSTATS/HMH100/
    - assets/pdfs/FACTSHEETS/THERMOSTATS/HMH200/
    - assets/pdfs/FACTSHEETS/THERMOSTATS/HMT5/
    - assets/pdfs/FACTSHEETS/THERMOSTATS/NGT/
    - assets/pdfs/FACTSHEETS/THERMOSTATS/NGTWIFI/
    - assets/pdfs/FACTSHEETS/THERMOSTATS/TPS/
    - assets/pdfs/FACTSHEETS/TTB/
    # Instructions
    - assets/pdfs/INSTRUCTIONS/
    - assets/pdfs/INSTRUCTIONS/CBM/
    - assets/pdfs/INSTRUCTIONS/HMHCAB/
    - assets/pdfs/INSTRUCTIONS/HMHMAT/
    - assets/pdfs/INSTRUCTIONS/ICEANDSNOW/
    - assets/pdfs/INSTRUCTIONS/PKC/
    - assets/pdfs/INSTRUCTIONS/PKM/
    - assets/pdfs/INSTRUCTIONS/THERMOSTATS/
    - assets/pdfs/INSTRUCTIONS/THERMOSTATS/HMH100/
    - assets/pdfs/INSTRUCTIONS/THERMOSTATS/HMH200/
    - assets/pdfs/INSTRUCTIONS/THERMOSTATS/HMT5/
    - assets/pdfs/INSTRUCTIONS/THERMOSTATS/NGT/
    - assets/pdfs/INSTRUCTIONS/THERMOSTATS/NGTWIFI/
    - assets/pdfs/INSTRUCTIONS/THERMOSTATS/TPS/
    # Case studies
    - assets/pdfs/CASESTUDIES/
    - assets/pdfs/CASESTUDIES/frontpages/

flutter_native_splash:
  color: "#111111"
  image: assets/images/splash_logo_final_white.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/splash_logo_final_white.png
    icon_background_color: "#111111"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/512_x_512_app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/512_x_512_app_icon.png
