// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHAzxbdUVPaBI4I6WXquI_DT308ZwuBsY',
    appId: '1:59927376997:ios:a4c05cfecb90cabb43c28c',
    messagingSenderId: '59927376997',
    projectId: 'hm-hc-app',
    storageBucket: 'hm-hc-app.firebasestorage.app',
    iosBundleId: 'uk.hmhcapp.ios',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBctUozeKBLzBatrc81ZBb5g3euo250koI',
    appId: '1:59927376997:android:b52578e0b1a7d16e43c28c',
    messagingSenderId: '59927376997',
    projectId: 'hm-hc-app',
    storageBucket: 'hm-hc-app.firebasestorage.app',
  );

}